//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum xwii_event_types {
  EVENT_KEY,
  EVENT_ACCEL,
  EVENT_IR,
  EVENT_BALANCE_BOARD,
  EVENT_MOTION_PLUS,
  EVENT_PRO_CONTROLLER_KEY,
  EVENT_PRO_CONTROLLER_MOVE,
  EVENT_WATCH,
  EVENT_CLASSIC_CONTROLLER_KEY,
  EVENT_CLASSIC_CONTROLLER_MOVE,
  EVENT_NUNCHUK_KEY,
  EVENT_NUNCHUK_MOVE,
  EVENT_DRUMS_KEY,
  EVENT_DRUMS_MOVE,
  EVENT_GUITAR_KEY,
  EVENT_GUITAR_MOVE,
  EVENT_GONE,
  EVENT_NUM
}
