//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum xwii_event_keys {
  KEY_LEFT,
  KEY_RIGHT,
  KEY_UP,
  KEY_DOWN,
  KEY_A,
  KEY_B,
  KEY_PLUS,
  KEY_MINUS,
  KEY_HOME,
  KEY_ONE,
  KEY_TWO,
  KEY_X,
  KEY_Y,
  KEY_TL,
  KEY_TR,
  KEY_ZL,
  KEY_ZR,
  KEY_THUMBL,
  KEY_THUMBR,
  KEY_C,
  KEY_Z,
  KEY_STRUM_BAR_UP,
  KEY_STRUM_BAR_DOWN,
  KEY_FRET_FAR_UP,
  KEY_FRET_UP,
  KEY_FRET_MID,
  KEY_FRET_LOW,
  KEY_FRET_FAR_LOW,
  KEY_NUM
}
