//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace WiiMoteSpotlight.Lib.XWiiMote.Swig {

public class xwiimote {
  public static readonly string NAME_CORE = xwiimotePINVOKE.NAME_CORE_get();
  public static readonly string NAME_ACCEL = xwiimotePINVOKE.NAME_ACCEL_get();
  public static readonly string NAME_IR = xwiimotePINVOKE.NAME_IR_get();
  public static readonly string NAME_MOTION_PLUS = xwiimotePINVOKE.NAME_MOTION_PLUS_get();
  public static readonly string NAME_NUNCHUK = xwiimotePINVOKE.NAME_NUNCHUK_get();
  public static readonly string NAME_CLASSIC_CONTROLLER = xwiimotePINVOKE.NAME_CLASSIC_CONTROLLER_get();
  public static readonly string NAME_BALANCE_BOARD = xwiimotePINVOKE.NAME_BALANCE_BOARD_get();
  public static readonly string NAME_PRO_CONTROLLER = xwiimotePINVOKE.NAME_PRO_CONTROLLER_get();
  public static readonly string NAME_DRUMS = xwiimotePINVOKE.NAME_DRUMS_get();
  public static readonly string NAME_GUITAR = xwiimotePINVOKE.NAME_GUITAR_get();
}

}
