//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace WiiMoteSpotlight.Lib.XWiiMote.Swig {

public enum xwii_drums_abs {
  DRUMS_ABS_PAD,
  DRUMS_ABS_CYMBAL_LEFT,
  DRUMS_ABS_CYMBAL_RIGHT,
  DRUMS_ABS_TOM_LEFT,
  DRUMS_ABS_TOM_RIGHT,
  DRUMS_ABS_TOM_FAR_RIGHT,
  DRUMS_ABS_BASS,
  DRUMS_ABS_HI_HAT,
  DRUMS_ABS_NUM
}

}
