//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace WiiMoteSpotlight.Lib.XWiiMote.Swig {

public enum xwii_iface_type {
  IFACE_CORE = 0x000001,
  IFACE_ACCEL = 0x000002,
  IFACE_IR = 0x000004,
  IFACE_MOTION_PLUS = 0x000100,
  IFACE_NUNCHUK = 0x000200,
  IFACE_CLASSIC_CONTROLLER = 0x000400,
  IFACE_BALANCE_BOARD = 0x000800,
  IFACE_PRO_CONTROLLER = 0x001000,
  IFACE_DRUMS = 0x002000,
  IFACE_GUITAR = 0x004000,
  IFACE_ALL = IFACE_CORE|IFACE_ACCEL|IFACE_IR|IFACE_MOTION_PLUS|IFACE_NUNCHUK|IFACE_CLASSIC_CONTROLLER|IFACE_BALANCE_BOARD|IFACE_PRO_CONTROLLER|IFACE_DRUMS|IFACE_GUITAR,
  IFACE_WRITABLE = 0x010000
}

}
